global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'weather_probe'
    metrics_path: /metrics
    scrape_interval: 3m
    scrape_timeout: 2s
    static_configs:
      - targets: ['weather-probe:80']