{
 "title": "Weather Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Heat Index",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heat_index" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Heat Index",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "heat_index" }
   ]
  }
 ]
}